name = "cloudmysite-html-worker"
type = "javascript"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2024-07-01"

main = "index.js"         # ✅ This tells Wrangler what to run

[site]
bucket = "."              # ✅ HTML files are in the root
entry-point = "."         # ✅ index.js is in the root
