name = "gym-vbsingh041979"
type = "javascript"

account_id = "d12521e2e1b9c898650c952766c9b8e2"
workers_dev = true
compatibility_date = "2024-07-01"


[site]
bucket = "."        # ✅ Where your HTML files are
