name = "cloudmysite-html-worker"
type = "javascript"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2024-07-01"

main = "index.js"   # ✅ Required

[site]
bucket = "."        # ✅ Where your HTML files are
