- uses: actions/checkout@v3

- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Install Wrangler 4
  run: npm install -g wrangler@4

- name: Publish with Wrangler 4
  run: wrangler publish
  env:
    CLOUDFLARE_API_TOKEN: "SYdBGD09f_VSiu1_j-UePII1hxVZDKWTRaQvDhxr"